/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_LDNetDiagnoService_LDNetSocket */

#ifndef _Included_com_netease_LDNetDiagnoService_LDNetSocket
#define _Included_com_netease_LDNetDiagnoService_LDNetSocket
#ifdef __cplusplus
extern "C" {
#endif
#undef com_netease_LDNetDiagnoService_LDNetSocket_PORT
#define com_netease_LDNetDiagnoService_LDNetSocket_PORT 80L
#undef com_netease_LDNetDiagnoService_LDNetSocket_CONN_TIMES
#define com_netease_LDNetDiagnoService_LDNetSocket_CONN_TIMES 4L
/*
 * Class:     com_netease_LDNetDiagnoService_LDNetSocket
 * Method:    startJNITelnet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_netease_LDNetDiagnoService_LDNetSocket_startJNITelnet
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
